image_finetune: true

output_dir: "outputs/renderer"
pretrained_model_path: "../base_ckpt/realisticVisionV51_v51VAE"
clip_model_path: "../base_ckpt/clip-vit-base-patch32"

cur_image_guider_checkpoint_path: ""
referencenet_checkpoint_path: ""

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

description: "### Train Info: Renderer ###"

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 24
    temporal_attention_dim_div         : 1
    zero_initialize                    : true


train_data:
  data_folder: "../data/sample_data"
  sample_size:  512 # for 40G 256
  sample_stride: 1
  sample_num: 100
  sample_n_frames: 8
  clip_model_path: "../base_ckpt/clip-vit-base-patch32"

  # pad_to_square+resize, resize, pad_to_16
  pad_mode: "pad_to_16"


trainable_modules:
  # - "motion_modules."
  - "."

unet_checkpoint_path: ""

fusion_blocks: "full"

learning_rate:    1.e-5
train_batch_size: 1
use_PE: True
PE_type: 'abs'
use_RP: True
use_TP: True 
no_refnet: False 
win_size: 10
use_diff_clip: True



feature_type: 'text'
TP_ckpt_path: ''
RP_fusion_type: 'spatial'
use_mask_for_loss: False
use_binary_RP: True  
RP_threshold: 0.2

PE_time_max: 100
PE_time_interval: 5


is_train_TP: False 
is_train_text_encoder: False

max_train_epoch:      -1
max_train_steps:      600000
checkpointing_epochs: -1
checkpointing_steps:  20000
gradient_accumulation_steps: 1


global_seed: 42
mixed_precision_training: True 
enable_xformers_memory_efficient_attention: True


is_debug: False
